### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by DariushMazlumi** [livace/atom-gpp#12]
Hi
I have just installed this package and encountered this error when I pressed F9 to compile and run a file:
<img width="1280" alt="Screen Shot 1398-10-05 at 23 38 33" src="https://user-images.githubusercontent.com/30628454/71489023-d8468000-2838-11ea-9751-93c50a3d4cbc.png">
I'm using atom in macOS 10.15 and I have installed Xcode and its stuff.
I also tried disabling other non-core packages and restarting the atom, which didn't solve the problem.
this issue has already been reported: https://github.com/livace/atom-gpp/issues/9
but the user who opened the issue, closed it himself without providing any reason.

by the way, this is the full error report:
steps to reproduce:

1. install this package
2. press fn + F9

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [gpp](https://github.com/livace/atom-gpp) package 0.4.3

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp/index.js:57:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -6:48.6.0 core:backspace (input.hidden-input)
  2x -6:43.4.0 editor:newline (input.hidden-input)
     -6:38.7.0 core:backspace (input.hidden-input)
     -6:36.5.0 editor:newline (input.hidden-input)
     -6:34.1.0 core:backspace (input.hidden-input)
     -6:31.7.0 editor:newline (input.hidden-input)
     -6:30.7.0 core:backspace (input.hidden-input)
  2x -6:28.6.0 editor:newline (input.hidden-input)
     -6:26.8.0 core:backspace (input.hidden-input)
     -6:23.9.0 gcc-make-run:compile-run (input.hidden-input)
     -3:02.6.0 tree-view:remove (span.name.icon.icon-file-text)
  3x -2:55.5.0 editor:newline (input.hidden-input)
     -2:47.4.0 gpp-compiler:compile (input.hidden-input)
     -1:54.1.0 gpp:compile-run (input.hidden-input)
```

### Non-Core Packages

```
atom-smart-template 0.3.2 
autosave-onchange 1.5.1 
gcc-make-run 0.2.12 
gpp 0.4.3 
gpp-compiler 3.0.7 
linter-gcc 0.7.1 
```

**Comment by nomaanh** [comment]
#include<iostream>
int main ()

{
std::cout<<"hello world"<<std::endl;

return 0;
}

try this...
I hope compile will be run

**Comment by nh-404** [comment]
#include <iostream>
#define PI 3.1416
int main ()

{

std::cout<<"value of PI: "<<PI <<std::endl;

return 0;
}
![Screenshot (11)](https://user-images.githubusercontent.com/63117803/78387576-6765ef80-7601-11ea-8958-e9ec7dff2c81.png)


please try this way
I hope compiler will be run

note:
you have need to write {std::} before & after (cout)

**Comment by DariushMazlumi** [comment]
hi @nomaanh 
since I opened this issue, I started using Windows. I have MinGW installed and added to the path. so I have all the requirements for using this package in windows as described in [description](https://atom.io/packages/gpp)
(a screenshot from MinGW)
<img width="1280" alt="Annotation 2020-04-04 201143" src="https://user-images.githubusercontent.com/30628454/78454932-7fe11300-76b0-11ea-87b3-f637c3b0540a.png">
(a screenshot from my system's path)
<img width="1280" alt="Annotation 2020-04-04 201300" src="https://user-images.githubusercontent.com/30628454/78454955-b6b72900-76b0-11ea-8416-e31878bb97d8.png">

steps to reproduce remained unchanged, also the package's version(0.4.3).
but atom's latest version (which is installed on my system) is updated to 1.45.0. and as I mentioned earlier, I tested this package on Windows 10, version 1909.

I also used the same code you provided, but I'm getting the same error again!
<img width="1280" alt="Annotation 2020-04-04 200031" src="https://user-images.githubusercontent.com/30628454/78454862-f16c9180-76af-11ea-991a-62f61248f86f.png">

full error report:
steps to reproduce:

1. install this package
2. write a simple code that you are sure it can be compiled (like @nomaanh 's code or mine or anything else)
3. hit F9 to compile and run it using gpp package.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp](https://github.com/livace/atom-gpp) package 0.4.3


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp/index.js:57:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
     -8:47.3.0 tree-view:move (li.file.entry.list-item.selected)
     -8:44.2.0 core:confirm (input.hidden-input)
     -7:52.5.0 intentions:highlight (input.hidden-input)
     -7:52.3.0 core:paste (input.hidden-input)
     -7:50.6.0 intentions:highlight (input.hidden-input)
     -7:50.4.0 core:copy (input.hidden-input)
     -7:49.6.0 core:undo (input.hidden-input)
     -7:48.1.0 intentions:highlight (input.hidden-input)
     -7:48 core:select-all (input.hidden-input)
     -7:47.3.0 core:backspace (input.hidden-input)
     -7:34.6.0 intentions:highlight (input.hidden-input)
     -7:34.4.0 core:paste (input.hidden-input)
     -7:23.5.0 gpp:compile-run (input.hidden-input)
```

### Non-Core Packages

```
atom-smart-template 0.3.2 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
gcc-make-run 0.2.12 
gpp 0.4.3 
intentions 1.1.5 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
```

**Comment by Guide7** [comment]
Hi, I have the same problem I'm using Linux Ubuntu. Last time I had succesfully compiled my code but with using f10 instead of f9. I really don't know what to do.

**Comment by Archay** [comment]
Weirdly f10 works after compiling, yet ctrl + f9 does not.

**Comment by livace** [comment]
Hi there! 

I'm really sorry that this project was abandoned for nearly two years. 

But now I finally had time to fix this annoying bug. Everything should work in the latest release 0.5.0

Thank you for your patience

**Comment by manraj1729** [comment]
hey thanks alot for fixing works like a charm now :)
