### ISSUE TITLE
Compiling doesn't work when there is a whitespace in the filepath

### ISSUE THREAD

**Issue by tombeek111** [livace/atom-gpp#2]
I got an error when i wanted to compile a file with a whitespace in it's path. This is the fix for index.js:

    const options = (file.path + ' -o ' + compiledPath + ' ' + atom.config.get('gpp.compilerOptions')).replace(/[\s{2,}]+/g, ' ').trim();
    path.join(filePath.dir, filePath.name);
    console.log(options.split(' '));
    const child = child_process.spawn('g++', options.split(' '), {
      cwd: filePath.dir
    });

To 

      const options = atom.config.get('gpp.compilerOptions').replace(/[\s{2,}]+/g, ' ').trim();
      path.join(filePath.dir, filePath.name);
      var new_options = [file.path,'-o',compiledPath]
      if (options != ""){
        new_options = new_options.concat(options.split(' '));
      }
      const child = child_process.spawn('g++', new_options, {
        cwd: filePath.dir
      });

The problem was that split(' ') would split on the whitespaces in the filename.

**Comment by livace** [comment]
Thank you! I published patch. Now you can update package
