### ISSUE TITLE
The Compilation Panel Doesn't show anything

### ISSUE THREAD

**Issue by ShakilAhmedShaj** [livace/atom-gpp#5]
![image](https://user-images.githubusercontent.com/15268903/38100752-1ca3df06-3333-11e8-9825-7337699b3426.png)

I have run my code successfully but the panel doesn't show anything. 

Please Help

**Comment by livace** [comment]
It actually shouldn't. It shows errors if any. You can hide it using Ctrl+Shift+T

**Comment by ShakilAhmedShaj** [comment]
Thanks a lot
